// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// adaptive_partition_signed_1d
List adaptive_partition_signed_1d(Function f, double lower, double upper, int n_grid);
RcppExport SEXP _StratMonteCarlo_adaptive_partition_signed_1d(SEXP fSEXP, SEXP lowerSEXP, SEXP upperSEXP, SEXP n_gridSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Function >::type f(fSEXP);
    Rcpp::traits::input_parameter< double >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< double >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< int >::type n_grid(n_gridSEXP);
    rcpp_result_gen = Rcpp::wrap(adaptive_partition_signed_1d(f, lower, upper, n_grid));
    return rcpp_result_gen;
END_RCPP
}
// montecarlo_integrate
double montecarlo_integrate(Function f, NumericVector lower, NumericVector upper, int n_samples, bool partition, int dim, int n_grid, int n_grid_per_dim);
RcppExport SEXP _StratMonteCarlo_montecarlo_integrate(SEXP fSEXP, SEXP lowerSEXP, SEXP upperSEXP, SEXP n_samplesSEXP, SEXP partitionSEXP, SEXP dimSEXP, SEXP n_gridSEXP, SEXP n_grid_per_dimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Function >::type f(fSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< int >::type n_samples(n_samplesSEXP);
    Rcpp::traits::input_parameter< bool >::type partition(partitionSEXP);
    Rcpp::traits::input_parameter< int >::type dim(dimSEXP);
    Rcpp::traits::input_parameter< int >::type n_grid(n_gridSEXP);
    Rcpp::traits::input_parameter< int >::type n_grid_per_dim(n_grid_per_dimSEXP);
    rcpp_result_gen = Rcpp::wrap(montecarlo_integrate(f, lower, upper, n_samples, partition, dim, n_grid, n_grid_per_dim));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_StratMonteCarlo_adaptive_partition_signed_1d", (DL_FUNC) &_StratMonteCarlo_adaptive_partition_signed_1d, 4},
    {"_StratMonteCarlo_montecarlo_integrate", (DL_FUNC) &_StratMonteCarlo_montecarlo_integrate, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_StratMonteCarlo(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
