# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

adaptive_partition_signed_1d <- function(f, lower, upper, n_grid = 1000L) {
    .Call(`_StratMonteCarlo_adaptive_partition_signed_1d`, f, lower, upper, n_grid)
}

montecarlo_integrate_cpp <- function(f, lower, upper, n_samples, partition = FALSE, dim = 1L, n_grid = 1000L, n_grid_per_dim = 5L) {
    .Call(`_StratMonteCarlo_montecarlo_integrate`, f, lower, upper, n_samples, partition, dim, n_grid, n_grid_per_dim)
}

