# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

montecarlo_integrate_cpp <- function(f_input, lower, upper, n_samples, partition = FALSE, dim = 1L, expr = "", vars = NULL, importance_sampling = FALSE, is_distribution = "normal", is_params = NULL, step = 100L) {
    .Call(`_StratMonteCarlo_montecarlo_integrate_cpp`, f_input, lower, upper, n_samples, partition, dim, expr, vars, importance_sampling, is_distribution, is_params, step)
}

